name: termite
base: core18
version: '0.15.3-55-0classic1'
summary: VTE-based terminal
description: |
  A keyboard-centric VTE-based terminal, aimed at use within a window manager
  with tiling and/or tabbing support.

# icon: termite.png

grade: stable
confinement: classic


apps:
  termite:
    command: usr/bin/termite
    desktop: usr/share/applications/termite.desktop


build-packages:
  - cmake
  - quilt
  - pkgconf


parts:
  fribidi:
    plugin: meson
    source: https://github.com/fribidi/fribidi.git
    source-tag: v1.0.7
    meson-parameters: 
      - --prefix=/usr
      - -Ddocs=false
    stage:
      - -usr/share/doc
      - -usr/share/man


  vte-ng:
    after: [ fribidi ]
    plugin: meson
    source: https://github.com/sd-hd/vte-ng.git
    source-tag: 0.58.2-ng
    meson-parameters: 
      - --prefix=/usr
      - -Ddocs=false
    build-packages:
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgnutls28-dev
      - libgtk-3-dev
      - libpango1.0-dev
      - libpcre2-dev
      - libxml2-utils
      - zlib1g-dev
    stage-packages:
      - libatk1.0-0
      - libcairo2
      - libglib2.0-0
      - libgnutls30
      - libgtk-3-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpcre2-8-0
    stage:
      - -usr/share/doc
      - -usr/share/man


  termite:
    after: [ vte-ng ]
    plugin: make
    source: https://github.com/sd-hd/termite.git
    source-tag: 'v15.3'
    source-type: git
    build-packages:
      - libtool
      - libdconf-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libglib3.0-cil-dev
      - libgnutls28-dev
      - libgtk-3-dev
      - libpcre2-dev
      - libx11-dev
      - libxml2-utils
      - libsm-dev
      - uuid-dev
      - valac
    stage-packages:
      - libatk1.0-0
      - libgirepository-1.0-1
      - libglib3.0-cil
      - libgtk-3-0
      - libpango-1.0-0
      - libcairo2
      - libuuid1
      - libx11-6
      - libgdk-pixbuf2.0-0
    organize:
      config: etc/xdg/termite/config
